// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDf1JKixSUiXLDE4EBof7D4Y9b4eSgjgQ',
    appId: '1:1008455298981:web:e144390af0f706d1c0824c',
    messagingSenderId: '1008455298981',
    projectId: 'kdh-omninews',
    authDomain: 'kdh-omninews.firebaseapp.com',
    storageBucket: 'kdh-omninews.firebasestorage.app',
    measurementId: 'G-WC949NF0CD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2TuHUHq7KMI9FQU0xSGDvlThIo1GNyrw',
    appId: '1:1008455298981:android:31ee11ca26020063c0824c',
    messagingSenderId: '1008455298981',
    projectId: 'kdh-omninews',
    storageBucket: 'kdh-omninews.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzSdJ4LcSGtGi9HamYZDvw48rXVBWR378',
    appId: '1:1008455298981:ios:7bd18f09a463c460c0824c',
    messagingSenderId: '1008455298981',
    projectId: 'kdh-omninews',
    storageBucket: 'kdh-omninews.firebasestorage.app',
    iosBundleId: 'com.example.omninewsFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzSdJ4LcSGtGi9HamYZDvw48rXVBWR378',
    appId: '1:1008455298981:ios:7bd18f09a463c460c0824c',
    messagingSenderId: '1008455298981',
    projectId: 'kdh-omninews',
    storageBucket: 'kdh-omninews.firebasestorage.app',
    iosBundleId: 'com.example.omninewsFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDf1JKixSUiXLDE4EBof7D4Y9b4eSgjgQ',
    appId: '1:1008455298981:web:9bfeda86a1568cf4c0824c',
    messagingSenderId: '1008455298981',
    projectId: 'kdh-omninews',
    authDomain: 'kdh-omninews.firebaseapp.com',
    storageBucket: 'kdh-omninews.firebasestorage.app',
    measurementId: 'G-FNR9S5VE65',
  );
}
